title: StarForge Armory Documentation
description: Public documentation for StarForge Armory Arma 3 modules, factions, classnames, and gadgets.
url: "https://starforgedev.github.io"
baseurl: "/SFA_Documentation"
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default
